---
:secret_key_base: 629f6a3ecb8ad965a3bc8b60727bf29fd8ca8ca9bffb89c9c98d32948eac8561023af3bf22566fd5e58aa47c71a1c6622bcd73fa789a59453286cc213ad9ff77
:litestream:
  :access_key_id: YOUR_S3_ACCESS_KEY
  :secret_access_key: YOUR_S3_SECRET_KEY
